openapi: 3.0.0
info:
  title: Auth API
  description: API para autenticación con JWT
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Registro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: Usuario registrado
  /auth/login:
    post:
      summary: Login
      responses:
        '200':
          description: Token generado
components:
  schemas:
    RegisterDto:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string